{
  "Default": {
    "FileName": "Default",
    "FilePath": "C:\\Users\\Summit\\AppData\\Roaming\\TwoOkNotes\\FileSettings.json",
    "Id": 0,
    "LastModifiedDate": "2025-02-19T12:29:27.0148388-05:00"
  },
  "Untitled17.isf": {
    "FileName": "Untitled17.isf",
    "FilePath": "C:\\Users\\Summit\\Source\\Repos\\OkNotes\\TwoOkNotes\\TempNoteFolder\\Untitled17.isf",
    "Id": 1,
    "LastModifiedDate": "2025-02-19T12:29:27.0139484-05:00"
  }
}